import type { DemoState, Person } from "./types";

const now = "2026-10-01T10:00:00.000Z";

function extraPeople(): Person[] {
  const names: [string, string, "m" | "f"][] = [
    ["Алексей", "Морозов", "m"],
    ["Ирина", "Котова", "f"],
    ["Максим", "Ершов", "m"],
    ["Светлана", "Лапина", "f"],
    ["Роман", "Жуков", "m"],
    ["Татьяна", "Сидорова", "f"],
    ["Павел", "Ковалёв", "m"],
    ["Юлия", "Медведева", "f"],
    ["Андрей", "Савельев", "m"],
    ["Марина", "Тихонова", "f"],
    ["Денис", "Кузнецов", "m"],
    ["Оксана", "Васильева", "f"],
    ["Илья", "Гордеев", "m"],
    ["Наталья", "Фролова", "f"],
    ["Егор", "Михайлов", "m"],
    ["Алина", "Сорокина", "f"],
    ["Владимир", "Петров", "m"],
    ["Екатерина", "Андреева", "f"],
    ["Никита", "Лебедев", "m"],
    ["Дарья", "Новикова", "f"],
    ["Станислав", "Орлов", "m"],
    ["Полина", "Зайцева", "f"],
    ["Артур", "Борисов", "m"],
    ["Ксения", "Макарова", "f"],
    ["Глеб", "Власов", "m"],
    ["Вероника", "Ефимова", "f"],
    ["Тимур", "Соловьёв", "m"],
    ["Алёна", "Гусева", "f"],
  ];
  const depts = ["Проекты", "Производство", "Финансы"] as const;
  const titles = [
    "Специалист",
    "Инженер",
    "Аналитик",
    "Координатор",
    "Технолог",
    "Экономист",
  ];
  const managers = ["dmitry", "sergey", "anna"];
  const grades: Array<"A" | "B" | "C"> = ["A", "B", "C"];

  return names.map(([first, last, gender], i) => {
    const grade = grades[i % 3];
    const years = (i % 9) + 1;
    const dept = depts[i % 3];
    const burnableBase = grade === "A" ? 8000 : grade === "B" ? 5000 : 3500;
    const spent = (i * 173) % Math.min(burnableBase, 2800);
    return {
      id: `e${i + 1}`,
      name: `${first} ${last}`,
      role: "employee" as const,
      title: titles[i % titles.length],
      department: dept,
      grade,
      years,
      managerId: managers[i % managers.length],
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: i % 5 === 0,
      burnable: burnableBase - spent,
      burnableUntil: "2027-10-01",
      durable: years * 500,
      frozen: false,
      city: i % 2 === 0 ? "Екатеринбург" : "Челябинск",
      email: `e${i + 1}@altair.demo`,
      phone: `+7 900 100 ${String(10 + i).padStart(2, "0")} ${String(20 + i).padStart(2, "0")}`,
      birthDate: `${1985 + (i % 15)}-${String((i % 12) + 1).padStart(2, "0")}-15`,
      gender,
      segmentIds: ["seg-all"],
    };
  });
}

export function createSeed(): DemoState {
  const core: Person[] = [
    {
      id: "maria",
      name: "Мария Соколова",
      role: "employee",
      title: "Менеджер проектов",
      department: "Проекты",
      grade: "B",
      years: 4,
      managerId: "dmitry",
      onboardingDone: false,
      needsQuizDone: false,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: false,
      burnable: 5000,
      burnableUntil: "2027-10-01",
      durable: 2000,
      frozen: false,
      city: "Екатеринбург",
      email: "maria.sokolova@altair.demo",
      phone: "+7 900 111 22 33",
      birthDate: "1994-05-12",
      gender: "f",
      segmentIds: ["seg-all"],
    },
    {
      id: "elena",
      name: "Елена Крылова",
      role: "decret",
      title: "Аналитик",
      department: "Проекты",
      grade: "B",
      years: 3,
      managerId: "dmitry",
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: false,
      burnable: 3500,
      burnableUntil: "2027-10-01",
      durable: 1500,
      frozen: false,
      city: "Екатеринбург",
      email: "elena.krylova@altair.demo",
      segmentIds: ["seg-all", "seg-decret"],
    },
    {
      id: "igor",
      name: "Игорь Волков",
      role: "vip",
      title: "Советник правления",
      department: "Проекты",
      grade: null,
      years: 12,
      managerId: null,
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: true,
      burnable: 0,
      burnableUntil: null,
      durable: 0,
      frozen: false,
      city: "Москва",
      email: "igor.volkov@altair.demo",
      segmentIds: ["seg-vip"],
    },
    {
      id: "dmitry",
      name: "Дмитрий Новиков",
      role: "manager",
      title: "Руководитель проектов",
      department: "Проекты",
      grade: "A",
      years: 8,
      managerId: null,
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: false,
      burnable: 8000,
      burnableUntil: "2027-10-01",
      durable: 4000,
      frozen: false,
      city: "Екатеринбург",
      email: "dmitry.novikov@altair.demo",
      segmentIds: ["seg-all"],
    },
    {
      id: "anna",
      name: "Анна Лебедева",
      role: "hr",
      title: "HR Business Partner",
      department: "Финансы",
      grade: "A",
      years: 6,
      managerId: null,
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: false,
      burnable: 8000,
      burnableUntil: "2027-10-01",
      durable: 3000,
      frozen: false,
      city: "Екатеринбург",
      email: "anna.lebedeva@altair.demo",
      segmentIds: ["seg-all"],
    },
    {
      id: "pavel",
      name: "Павел Орлов",
      role: "admin",
      title: "Администратор платформы",
      department: "Финансы",
      grade: "A",
      years: 5,
      managerId: null,
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: false,
      burnable: 8000,
      burnableUntil: "2027-10-01",
      durable: 2500,
      frozen: false,
      city: "Екатеринбург",
      email: "pavel.orlov@altair.demo",
      segmentIds: ["seg-all"],
    },
    {
      id: "olga",
      name: "Ольга Смирнова",
      role: "employee",
      title: "Инженер",
      department: "Производство",
      grade: "C",
      years: 2,
      managerId: "sergey",
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: false,
      burnable: 2100,
      burnableUntil: "2027-10-01",
      durable: 1000,
      frozen: false,
      city: "Челябинск",
      email: "olga.smirnova@altair.demo",
      segmentIds: ["seg-all"],
    },
    {
      id: "sergey",
      name: "Сергей Панин",
      role: "manager",
      title: "Начальник цеха",
      department: "Производство",
      grade: "A",
      years: 11,
      managerId: null,
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: false,
      burnable: 6200,
      burnableUntil: "2027-10-01",
      durable: 5500,
      frozen: false,
      city: "Челябинск",
      email: "sergey.panin@altair.demo",
      segmentIds: ["seg-all"],
    },
    {
      id: "nina",
      name: "Нина Белова",
      role: "employee",
      title: "Бухгалтер",
      department: "Финансы",
      grade: "B",
      years: 5,
      managerId: "anna",
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: "prog-std",
      dmsStatus: "active",
      dmsExpiresAt: "2027-09-30",
      burnNoticesSent: 0,
      flexibleSchedule: false,
      burnable: 1800,
      burnableUntil: "2027-10-01",
      durable: 2500,
      frozen: false,
      city: "Екатеринбург",
      email: "nina.belova@altair.demo",
      segmentIds: ["seg-all"],
    },
    {
      id: "kirill",
      name: "Кирилл Фомин",
      role: "employee",
      title: "Разработчик",
      department: "Финансы",
      grade: "B",
      years: 3,
      managerId: "pavel",
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: true,
      burnable: 3500,
      burnableUntil: "2027-10-01",
      durable: 1500,
      frozen: false,
      city: "Екатеринбург",
      email: "kirill.fomin@altair.demo",
      segmentIds: ["seg-all"],
    },
    {
      id: "vera",
      name: "Вера Громова",
      role: "employee",
      title: "Специалист по закупкам",
      department: "Финансы",
      grade: "C",
      years: 1,
      managerId: "anna",
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: false,
      burnable: 3500,
      burnableUntil: "2027-10-01",
      durable: 500,
      frozen: false,
      city: "Екатеринбург",
      email: "vera.gromova@altair.demo",
      segmentIds: ["seg-all"],
    },
    {
      id: "anton",
      name: "Антон Рыбаков",
      role: "employee",
      title: "Мастер участка",
      department: "Производство",
      grade: "C",
      years: 7,
      managerId: "sergey",
      onboardingDone: true,
      needsQuizDone: true,
      dmsProgramId: null,
      dmsStatus: "none",
      dmsExpiresAt: null,
      burnNoticesSent: 0,
      flexibleSchedule: false,
      burnable: 0,
      burnableUntil: "2027-10-01",
      durable: 3200,
      frozen: false,
      exclusion: true,
      city: "Челябинск",
      email: "anton.rybakov@altair.demo",
      segmentIds: ["seg-all"],
    },
  ];

  return {
    version: 4,
    currentUserId: null,
    window: {
      title: "Окно выбора 2026",
      start: "2026-10-01",
      end: "2026-10-31",
      open: true,
      changeMode: "restrict",
      segmentIds: ["seg-all"],
    },
    settings: {
      lottery: true,
      transfers: true,
      charity: true,
      teamPools: true,
      surveys: true,
      news: true,
      socialProjects: true,
      startPackage: true,
      gamification: true,
      tour: true,
      balanceWheel: true,
      transferCommission: 0.25,
      transferMin: 100,
      charityMatch: 1,
      pointRubRate: 1,
      codeStockThreshold: 2,
      anomalyLargeSpend: 3000,
      supportSlaHours: 24,
      burnDefaultMonths: 12,
      passwordMinLength: 10,
      maxManualGrant: 5000,
    },
    segments: [
      {
        id: "seg-all",
        title: "Все сотрудники",
        sectionAllow: "all",
      },
      {
        id: "seg-decret",
        title: "Декрет",
        sectionAllow: ["rest", "growth", "care", "general"],
      },
      {
        id: "seg-vip",
        title: "ВИП",
        sectionAllow: ["general"],
      },
    ],
    news: [
      {
        id: "n1",
        title: "Окно выбора открыто до 31 октября",
        body: "Соберите пакет льгот и подтвердите набор до конца месяца.",
        published: true,
        at: "2026-10-01T08:00:00.000Z",
        comments: [],
      },
      {
        id: "n2",
        title: "Сгораемые баллы 2026",
        body: "Годовая квота действует до 1 октября 2027. Сначала списываются сгораемые.",
        published: true,
        at: "2026-09-28T10:00:00.000Z",
        comments: [
          {
            id: "nc1",
            personId: "kirill",
            body: "Удобно, что приоритет списания виден в истории.",
            at: "2026-09-28T12:00:00.000Z",
          },
        ],
      },
    ],
    banners: [
      {
        id: "b1",
        title: "Благотворительность с матчингом",
        body: "Компания удваивает ваш взнос в выбранный фонд.",
        href: "/app/charity",
        active: true,
      },
      {
        id: "b2",
        title: "Осенняя лотерея",
        body: "Билет — 200 баллов. Розыгрыш в конце окна выбора.",
        href: "/app/lottery",
        active: true,
      },
    ],
    people: [...core, ...extraPeople()],
    benefits: [
      {
        id: "dms-base",
        categoryId: "cat-dms",
        imageLabel: "Полис ДМС",
        attachments: [{ id: "att-dms-base", title: "Полис ДМС", kind: "pdf", href: "/docs/pdf-dms-base" }],
        title: "ДМС «Стандарт»",
        description:
          "Базовая программа добровольного медицинского страхования с поликлиникой и экстренной госпитализацией.",
        section: "health",
        type: "dms",
        price: 2800,
        supplier: "СК Рельеф",
        archived: false,
        conditions: "Одна базовая программа на сотрудника. Член семьи — отдельная заявка.",
        packageGrade: ["A", "B"],
      },
      {
        id: "dms-family",
        categoryId: "cat-dms",
        imageLabel: "Условия семьи",
        attachments: [{ id: "att-dms-family", title: "Условия семьи", kind: "pdf", href: "/docs/pdf-dms-family" }],
        title: "ДМС для члена семьи",
        description: "Подключение супруга или ребёнка к расширенной программе.",
        section: "health",
        type: "dms",
        price: 2200,
        supplier: "СК Рельеф",
        archived: false,
        conditions: "Возраст застрахованного до 65 лет включительно.",
      },
      {
        id: "dent",
        categoryId: "cat-well",
        imageLabel: "Прайс стоматологии",
        attachments: [{ id: "att-dent", title: "Прайс стоматологии", kind: "pdf", href: "/docs/pdf-dent" }],
        title: "Стоматология+",
        description: "Расширение покрытия: терапия и диагностика.",
        section: "health",
        type: "digital",
        price: 900,
        supplier: "СК Рельеф",
        archived: false,
        conditions: "Доступно при активной базовой программе ДМС.",
        packageGrade: ["A"],
      },
      {
        id: "hotel",
        categoryId: "cat-hotel",
        imageLabel: "Буклет отеля",
        attachments: [{ id: "att-hotel", title: "Буклет отеля", kind: "image", href: "/docs/image-hotel" }],
        title: "Сертификат отеля «Северные озёра»",
        description: "Ночь в загородном отеле. Код приходит сразу после покупки.",
        section: "rest",
        type: "certificate",
        price: 1800,
        supplier: "Северные озёра",
        archived: false,
        conditions: "Отмена после выдачи кода невозможна.",
        packageGrade: ["A", "B"],
        codes: ["OZ-4812", "OZ-4820", "OZ-4837", "OZ-4841"],
        usedCodes: [],
        codeExpiresAt: "2027-10-01",
      },
      {
        id: "camp",
        categoryId: "cat-kids",
        imageLabel: "Программа смены",
        attachments: [{ id: "att-camp", title: "Программа смены", kind: "pdf", href: "/docs/pdf-camp" }],
        title: "Детский лагерь «Кедр»",
        description: "Смена 14 дней с питанием и транспортом.",
        section: "care",
        type: "family",
        price: 3200,
        supplier: "Кедр",
        archived: false,
        conditions: "Нужны ФИО ребёнка и даты смены.",
      },
      {
        id: "kindergarten",
        categoryId: "cat-kids",
        imageLabel: "Правила компенсации",
        attachments: [
          { id: "att-kg", title: "Правила компенсации сада", kind: "pdf", href: "/docs/pdf-kg" },
        ],
        title: "Компенсация детского сада",
        description: "Часть оплаты частного сада за квартал.",
        section: "care",
        type: "family",
        price: 1800,
        supplier: "HR Альтаир",
        archived: false,
        conditions: "Укажите ФИО ребёнка. Проверка документов HR.",
      },
      {
        id: "club",
        categoryId: "cat-kids",
        imageLabel: "Каталог кружков",
        attachments: [
          { id: "att-club", title: "Каталог кружков", kind: "pdf", href: "/docs/pdf-club" },
        ],
        title: "Кружок или секция",
        description: "Оплата кружка, секции или репетитора на месяц.",
        section: "care",
        type: "family",
        price: 900,
        supplier: "HR Альтаир",
        archived: false,
        conditions: "ФИО ребёнка обязательно.",
      },
      {
        id: "gift-child",
        categoryId: "cat-kids",
        imageLabel: "Витрина подарков",
        attachments: [
          { id: "att-gift", title: "Витрина подарков", kind: "image", href: "/docs/image-gift" },
        ],
        title: "Подарок ребёнку",
        description: "Набор к дню рождения или 1 сентября.",
        section: "care",
        type: "family",
        price: 600,
        supplier: "Склад Альтаир",
        archived: false,
        conditions: "Укажите ФИО ребёнка. Доставка на офис.",
      },
      {
        id: "course",
        categoryId: "cat-learn",
        imageLabel: "Программа курса",
        attachments: [{ id: "att-course", title: "Программа курса", kind: "pdf", href: "/docs/pdf-course" }],
        title: "Курс «Управление проектами»",
        description: "Онлайн-программа на 6 недель. Доступ приходит на почту.",
        section: "growth",
        type: "digital",
        price: 1500,
        supplier: "Альтаир Академия",
        archived: false,
        conditions: "Лимит мест в группе — 20.",
        packageGrade: ["C"],
        seatsLeft: 18,
      },
      {
        id: "leave-day",
        categoryId: "cat-time",
        imageLabel: "Регламент отпуска",
        attachments: [{ id: "att-leave-day", title: "Регламент отпуска", kind: "pdf", href: "/docs/pdf-leave-day" }],
        title: "Дополнительный день отпуска",
        description: "Покупка дня отдыха. Требует согласования руководителя.",
        section: "general",
        type: "leave",
        price: 1200,
        supplier: "HR Альтаир",
        archived: false,
        conditions: "Недоступно при неотгулянном основном отпуске свыше 14 дней.",
      },
      {
        id: "merch",
        categoryId: "cat-merch",
        imageLabel: "Фото худи",
        attachments: [{ id: "att-merch", title: "Фото худи", kind: "image", href: "/docs/image-merch" }],
        title: "Худи с логотипом",
        description: "Хлопковое худи, размеры S–XXL. Доставка на офис.",
        section: "general",
        type: "physical",
        price: 700,
        supplier: "Склад Альтаир",
        archived: false,
        conditions: "Укажите размер в комментарии к заказу.",
      },
      {
        id: "fitness",
        categoryId: "cat-sport",
        imageLabel: "Карта клубов",
        attachments: [{ id: "att-fitness", title: "Карта клубов", kind: "pdf", href: "/docs/pdf-fitness" }],
        title: "Абонемент в фитнес на месяц",
        description: "Сеть залов «Ритм». Цифровой код доступа.",
        section: "general",
        type: "certificate",
        price: 1100,
        supplier: "Ритм",
        archived: false,
        conditions: "Код действует 30 дней с активации.",
        codes: ["FIT-2201", "FIT-2202", "FIT-2203"],
        usedCodes: [],
        limitPerPeriod: 1,
      },
      {
        id: "psych",
        categoryId: "cat-well",
        imageLabel: "Правила сессии",
        attachments: [{ id: "att-psych", title: "Правила сессии", kind: "pdf", href: "/docs/pdf-psych" }],
        title: "Консультация психолога",
        description: "Онлайн-сессия 50 минут. Выбор слота после покупки.",
        section: "health",
        type: "booking",
        price: 800,
        supplier: "Wellbeing Desk",
        archived: false,
        conditions: "Перенос не позднее чем за 24 часа.",
      },
      {
        id: "lang",
        categoryId: "cat-learn",
        imageLabel: "Расписание групп",
        attachments: [{ id: "att-lang", title: "Расписание групп", kind: "pdf", href: "/docs/pdf-lang" }],
        title: "Языковые курсы",
        description: "Групповые занятия английским два раза в неделю.",
        section: "growth",
        type: "digital",
        price: 1600,
        supplier: "Альтаир Академия",
        archived: false,
        conditions: "Старт групп 15 числа каждого месяца.",
        seatsLeft: 12,
      },
      {
        id: "flex",
        categoryId: "cat-time",
        imageLabel: "Положение о графике",
        attachments: [{ id: "att-flex", title: "Положение о графике", kind: "pdf", href: "/docs/pdf-flex" }],
        title: "Гибкий график",
        description: "Нефинансовая льгота: отметка в профиле без списания баллов.",
        section: "general",
        type: "non_financial",
        price: 0,
        supplier: "HR Альтаир",
        archived: false,
        conditions: "Согласование с руководителем вне платформы.",
      },
      {
        id: "cert-pay",
        categoryId: "cat-cert",
        imageLabel: "Форма компенсации",
        attachments: [{ id: "att-cert-pay", title: "Форма компенсации", kind: "pdf", href: "/docs/pdf-cert-pay" }],
        title: "Оплата сертификации",
        description: "Компенсация внешнего экзамена в пределах лимита.",
        section: "growth",
        type: "docs",
        price: 2000,
        supplier: "HR Альтаир",
        archived: false,
        conditions: "Загрузите счёт и подтверждение записи. Лимит 2000 баллов.",
        maxSum: 2000,
      },
      {
        id: "resort",
        categoryId: "cat-tour",
        imageLabel: "Схема базы",
        attachments: [{ id: "att-resort", title: "Схема базы", kind: "image", href: "/docs/image-resort" }],
        title: "База отдыха «Урал»",
        description: "Бронирование домика на выходные. Вместимость до 4 человек.",
        section: "rest",
        type: "booking",
        price: 2400,
        supplier: "Урал Резорт",
        archived: false,
        conditions: "Минимум 14 дней до заезда.",
      },
      {
        id: "vcard",
        categoryId: "cat-merch",
        imageLabel: "Условия карты",
        attachments: [{ id: "att-vcard", title: "Условия карты", kind: "pdf", href: "/docs/pdf-vcard" }],
        title: "Виртуальная карта 3000 ₽",
        description: "Номер карты направляется на корпоративную почту.",
        section: "general",
        type: "digital",
        price: 3000,
        supplier: "ПВК (симуляция)",
        archived: false,
        conditions: "Внешний сервис в демо симулируется выдачей кода VC-****.",
        codes: ["VC-9041", "VC-9042"],
        usedCodes: [],
      },
    ],
    cart: [],
    packageIds: [],
    orders: [
      {
        id: "ord-1001",
        personId: "olga",
        benefitId: "fitness",
        title: "Абонемент в фитнес на месяц",
        price: 1100,
        status: "done",
        createdAt: "2026-09-20T09:00:00.000Z",
        code: "FIT-2190",
      },
      {
        id: "ord-1002",
        personId: "nina",
        benefitId: "course",
        title: "Курс «Управление проектами»",
        price: 1500,
        status: "done",
        createdAt: "2026-09-22T11:30:00.000Z",
      },
      {
        id: "ord-1003",
        personId: "anton",
        benefitId: "leave-day",
        title: "Дополнительный день отпуска",
        price: 1200,
        status: "awaiting_approval",
        createdAt: "2026-09-28T14:10:00.000Z",
        approverId: "sergey",
        note: "1 день, 12 ноября",
      },
      {
        id: "ord-1004",
        personId: "kirill",
        benefitId: "merch",
        title: "Худи с логотипом",
        price: 700,
        status: "processing",
        createdAt: "2026-09-29T16:00:00.000Z",
        note: "размер L · доставка на офис",
        meta: { size: "L" },
        deliveryStatus: "print",
      },
    ],
    ledger: [
      {
        id: "led-1",
        personId: "maria",
        kind: "grant",
        amount: 5000,
        burnableDelta: 5000,
        durableDelta: 0,
        comment: "Годовая квота 2026",
        at: "2026-10-01T08:00:00.000Z",
        actorId: "system",
      },
      {
        id: "led-2",
        personId: "maria",
        kind: "grant",
        amount: 2000,
        burnableDelta: 0,
        durableDelta: 2000,
        comment: "Стаж 4 года × 500",
        at: "2026-10-01T08:00:00.000Z",
        actorId: "system",
      },
      {
        id: "led-3",
        personId: "olga",
        kind: "spend",
        amount: 1100,
        burnableDelta: -1100,
        durableDelta: 0,
        comment: "Абонемент в фитнес на месяц",
        at: "2026-09-20T09:00:00.000Z",
        actorId: "olga",
      },
      {
        id: "led-4",
        personId: "nina",
        kind: "spend",
        amount: 1500,
        burnableDelta: -1500,
        durableDelta: 0,
        comment: "Курс «Управление проектами»",
        at: "2026-09-22T11:30:00.000Z",
        actorId: "nina",
      },
      {
        id: "led-5",
        personId: "kirill",
        kind: "spend",
        amount: 700,
        burnableDelta: -700,
        durableDelta: 0,
        comment: "Худи с логотипом",
        at: "2026-09-29T16:00:00.000Z",
        actorId: "kirill",
      },
      {
        id: "led-6",
        personId: "anton",
        kind: "spend",
        amount: 1200,
        burnableDelta: -900,
        durableDelta: -300,
        comment: "Дополнительный день отпуска",
        at: "2026-09-28T14:10:00.000Z",
        actorId: "anton",
      },
    ],
    tickets: [
      {
        id: "t-seed-1",
        personId: "nina",
        topic: "Не вижу код курса",
        body: "Курс купила 22 сентября, письмо на почту не пришло. Можно продублировать доступ?",
        status: "open",
        createdAt: "2026-09-30T10:15:00.000Z",
        slaHours: 24,
        attachments: ["skrin-kursa.png"],
      },
    ],
    audit: [
      {
        id: "aud-1",
        at: now,
        actorId: "system",
        action: "seed",
        detail: "Демо-данные ГК «Альтаир» загружены (v4, полный скоуп)",
      },
    ],
    transfers: [],
    funds: [
      {
        id: "fund-1",
        title: "Фонд «Тёплый дом»",
        description: "Помощь семьям сотрудников в сложных ситуациях.",
        active: true,
      },
      {
        id: "fund-2",
        title: "«Дети Урала»",
        description: "Образовательные программы и лагеря для детей региона.",
        active: true,
      },
      {
        id: "fund-3",
        title: "Экология реки Чусовой",
        description: "Волонтёрские субботники и очистка берегов.",
        active: true,
      },
    ],
    donations: [],
    pools: [
      {
        id: "pool-1",
        title: "Тимбилдинг отдела проектов",
        description: "Выезд на базу в ноябре. Цель — 12 000 баллов.",
        goal: 12000,
        ownerId: "dmitry",
        open: true,
        contributions: [
          { personId: "dmitry", amount: 2000, at: "2026-09-25T10:00:00.000Z" },
          { personId: "kirill", amount: 500, at: "2026-09-26T11:00:00.000Z" },
        ],
      },
    ],
    lotteries: [
      {
        id: "lot-1",
        title: "Осенняя лотерея 2026",
        description: "Призовой фонд из несгораемых баллов и мерча.",
        ticketPrice: 200,
        open: true,
        drawn: false,
        prizes: [
          { id: "pz1", title: "Главный приз — 5 000 баллов", points: 5000 },
          { id: "pz2", title: "Второй приз — 2 000 баллов", points: 2000 },
          { id: "pz3", title: "Третий приз — 1 000 баллов", points: 1000 },
        ],
        tickets: [
          { id: "lt-1", personId: "kirill", at: "2026-09-29T12:00:00.000Z" },
          { id: "lt-2", personId: "nina", at: "2026-09-30T09:00:00.000Z" },
        ],
        winners: [],
      },
    ],
    surveys: [
      {
        id: "srv-1",
        title: "Приоритеты льгот 2027",
        description: "Что важнее в следующем окне выбора?",
        open: true,
        questions: [
          {
            id: "q1",
            text: "Какой раздел усилить в первую очередь?",
            options: ["Здоровье", "Отдых", "Развитие", "Забота о семье"],
          },
          {
            id: "q2",
            text: "Готовы ли вы переводить баллы коллегам?",
            options: ["Да", "С комиссией — нет", "Только на благотворительность"],
          },
        ],
        responses: [],
      },
    ],
    notifications: [
      {
        id: "nt-1",
        personId: "maria",
        title: "Окно выбора открыто",
        body: "До 31 октября можно подтверждать заказы.",
        at: "2026-10-01T08:05:00.000Z",
        read: false,
        href: "/app/catalog",
      },
    ],
    anomalies: [
      {
        id: "an-1",
        at: "2026-09-29T16:05:00.000Z",
        personId: "kirill",
        rule: "Крупная покупка подряд",
        detail: "За неделю два заказа на сумму выше порога мониторинга (сид).",
        status: "open",
      },
    ],
    suggestions: [
      {
        id: "sug-seed",
        personId: "kirill",
        title: "Компенсация обедов в столовой",
        body: "Часть обеда баллами, чтобы сгораемые не висели до октября.",
        at: "2026-09-29T09:00:00.000Z",
        status: "new",
      },
    ],
    promos: [
      {
        id: "promo-1",
        title: "Кэшбэк на развитие",
        section: "growth",
        cashbackPct: 10,
        budgetLeft: 50000,
        start: "2026-10-01",
        end: "2026-10-31",
        active: true,
        spent: 0,
        redemptions: 0,
      },
      {
        id: "promo-2",
        title: "Осенний кэшбэк на отдых",
        section: "rest",
        cashbackPct: 5,
        budgetLeft: 30000,
        start: "2026-10-01",
        end: "2026-10-31",
        active: true,
        spent: 1500,
        redemptions: 1,
      },
    ],
    badges: [
      { id: "bdg-order", title: "Первая льгота", description: "Оформили первый заказ", rule: "first_order" },
      { id: "bdg-charity", title: "Доброе дело", description: "Взнос в фонд", rule: "charity" },
      { id: "bdg-survey", title: "Голос команды", description: "Прошли опрос", rule: "survey" },
      { id: "bdg-lottery", title: "Участник розыгрыша", description: "Купили билет лотереи", rule: "lottery" },
      { id: "bdg-transfer", title: "Щедрая рука", description: "Перевели баллы коллеге", rule: "transfer" },
      { id: "bdg-pool", title: "Командный игрок", description: "Взнос в сбор", rule: "pool" },
    ],
    categoryLimits: [
      { section: "health", maxPerYear: 0, enabled: false },
      { section: "rest", maxPerYear: 5000, enabled: false },
      { section: "growth", maxPerYear: 4000, enabled: false },
      { section: "care", maxPerYear: 0, enabled: false },
      { section: "general", maxPerYear: 0, enabled: false },
    ],
    socialProjects: [
      {
        id: "sp-1",
        title: "Субботник на Чусовой",
        body: "Запись волонтёров на октябрь. Баллы не списываются — социальная инициатива.",
        active: true,
      },
      {
        id: "sp-2",
        title: "Донорский день",
        body: "Корпоративный донорский выезд 20 октября.",
        active: true,
      },
    ],
    categories: [
      { id: "cat-dms", section: "health", title: "Страхование" },
      { id: "cat-well", section: "health", title: "Wellbeing" },
      { id: "cat-hotel", section: "rest", title: "Проживание" },
      { id: "cat-tour", section: "rest", title: "Туризм" },
      { id: "cat-learn", section: "growth", title: "Обучение" },
      { id: "cat-cert", section: "growth", title: "Сертификация" },
      { id: "cat-kids", section: "care", title: "Дети" },
      { id: "cat-merch", section: "general", title: "Мерч" },
      { id: "cat-sport", section: "general", title: "Спорт" },
      { id: "cat-time", section: "general", title: "Время" },
    ],
    dms: {
      insurer: "СК «Рельеф»",
      included: [
        "Поликлиника и терапия",
        "Экстренная госпитализация",
        "Телемедицина 24/7",
        "Анализы по направлению",
      ],
      excluded: [
        "Эстетическая стоматология",
        "Санаторно-курортное лечение",
        "Плановая косметология",
      ],
      clinics: [
        {
          id: "cl1",
          title: "Клиника «Север»",
          address: "Екатеринбург, ул. Малышева, 36",
          profile: "терапия, диагностика",
        },
        {
          id: "cl2",
          title: "МЦ «УралМед»",
          address: "Екатеринбург, пр. Ленина, 48",
          profile: "стационар, экстренная помощь",
        },
        {
          id: "cl3",
          title: "Семейный центр «Олива»",
          address: "Челябинск, ул. Кирова, 12",
          profile: "педиатрия, семейная медицина",
        },
      ],
      programs: [
        {
          id: "prog-std",
          title: "ДМС «Стандарт»",
          benefitId: "dms-base",
          note: "Базовая программа сотрудника",
        },
        {
          id: "prog-family",
          title: "ДМС для члена семьи",
          benefitId: "dms-family",
          note: "Доплата баллами, возраст до 65",
        },
      ],
    },
    eventGrants: [
      {
        id: "ev-builder",
        title: "День строителя",
        amount: 500,
        burnable: true,
        audience: "builders",
        runAt: "2026-08-09",
        lastRunAt: null,
      },
      {
        id: "ev-ny",
        title: "Новый год",
        amount: 1000,
        burnable: true,
        audience: "all",
        runAt: "2026-12-25",
        lastRunAt: null,
      },
      {
        id: "ev-women",
        title: "8 марта",
        amount: 300,
        burnable: false,
        audience: "female",
        runAt: "2026-03-08",
        lastRunAt: null,
      },
      {
        id: "ev-men",
        title: "23 февраля",
        amount: 300,
        burnable: false,
        audience: "male",
        runAt: "2026-02-23",
        lastRunAt: null,
      },
      {
        id: "ev-year",
        title: "Ежегодное начисление",
        amount: 5000,
        burnable: true,
        audience: "all",
        runAt: "2026-10-01",
        lastRunAt: null,
      },
      {
        id: "ev-bday",
        title: "День рождения",
        amount: 300,
        burnable: false,
        audience: "all",
        runAt: "2026-10-01",
        lastRunAt: null,
      },
    ],
    roleMap: {
      employee: ["storefront"],
      decret: ["storefront"],
      vip: ["storefront"],
      manager: ["storefront", "console", "approvals"],
      hr: ["storefront", "console", "catalog_edit", "budgets", "approvals", "audit"],
      admin: [
        "storefront",
        "console",
        "catalog_edit",
        "budgets",
        "approvals",
        "audit",
        "settings",
      ],
    },
    emailTemplates: [
      {
        id: "tpl-window",
        title: "Старт окна выбора",
        body: "Открыто окно выбора льгот. Зайдите в кафетерий и подтвердите набор.",
      },
      {
        id: "tpl-burn",
        title: "Сгорание баллов",
        body: "Часть сгораемых баллов истекает. Успейте потратить остаток.",
      },
      {
        id: "tpl-order",
        title: "Статус заказа",
        body: "Статус вашего заказа обновлён. Подробности — в разделе «Заказы».",
      },
    ],
    integrations: [
      {
        id: "int-1c",
        title: "1С:ЗУП (симуляция)",
        status: "ok",
        detail: "Последняя синхронизация: сегодня 08:00. Реального канала нет.",
      },
      {
        id: "int-sso",
        title: "SSO (симуляция)",
        status: "warn",
        detail: "В демо вход без пароля. Канал не подключён.",
      },
      {
        id: "int-mail",
        title: "SMTP / почта",
        status: "down",
        detail: "Письма не отправляются — коды показываются в UI.",
      },
      {
        id: "int-pvk",
        title: "ПВК / Giftery",
        status: "warn",
        detail: "Выдача виртуальных карт симулируется локальными кодами.",
      },
    ],
  };
}

export const STORAGE_KEY = "cafeteria-demo-v4";

export const gradeBudgets: Record<"A" | "B" | "C", number> = {
  A: 8000,
  B: 5000,
  C: 3500,
};

export const loginAccounts = [
  {
    id: "maria",
    blurb: "Сотрудник · грейд B · пакет ещё не собран",
  },
  {
    id: "elena",
    blurb: "Декрет · без страховых разделов",
  },
  {
    id: "igor",
    blurb: "ВИП · только общие предложения",
  },
  {
    id: "dmitry",
    blurb: "Руководитель Марии · согласования",
  },
  {
    id: "anna",
    blurb: "HR · пульт",
  },
  {
    id: "pavel",
    blurb: "Админ · пульт и настройки",
  },
] as const;
